// Generated by gencpp from file mavros_msgs/AutopilotVersionResponse.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_AUTOPILOTVERSIONRESPONSE_H
#define MAVROS_MSGS_MESSAGE_AUTOPILOTVERSIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavros_msgs
{
template <class ContainerAllocator>
struct AutopilotVersionResponse_
{
  typedef AutopilotVersionResponse_<ContainerAllocator> Type;

  AutopilotVersionResponse_()
    : version()
    , success(false)  {
    }
  AutopilotVersionResponse_(const ContainerAllocator& _alloc)
    : version(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _version_type;
  _version_type version;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::mavros_msgs::AutopilotVersionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavros_msgs::AutopilotVersionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AutopilotVersionResponse_

typedef ::mavros_msgs::AutopilotVersionResponse_<std::allocator<void> > AutopilotVersionResponse;

typedef boost::shared_ptr< ::mavros_msgs::AutopilotVersionResponse > AutopilotVersionResponsePtr;
typedef boost::shared_ptr< ::mavros_msgs::AutopilotVersionResponse const> AutopilotVersionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavros_msgs::AutopilotVersionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavros_msgs::AutopilotVersionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mavros_msgs': ['/home/flytpod/flytos/src/flytOS/flyt_core/core_nodes/mavros/mavros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::AutopilotVersionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::AutopilotVersionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::AutopilotVersionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::AutopilotVersionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::AutopilotVersionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::AutopilotVersionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavros_msgs::AutopilotVersionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "100332dc23a0380d220694dccac63ae2";
  }

  static const char* value(const ::mavros_msgs::AutopilotVersionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x100332dc23a0380dULL;
  static const uint64_t static_value2 = 0x220694dccac63ae2ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavros_msgs::AutopilotVersionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavros_msgs/AutopilotVersionResponse";
  }

  static const char* value(const ::mavros_msgs::AutopilotVersionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavros_msgs::AutopilotVersionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string version\n\
bool success\n\
\n\
";
  }

  static const char* value(const ::mavros_msgs::AutopilotVersionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavros_msgs::AutopilotVersionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.version);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AutopilotVersionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavros_msgs::AutopilotVersionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavros_msgs::AutopilotVersionResponse_<ContainerAllocator>& v)
  {
    s << indent << "version: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.version);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_AUTOPILOTVERSIONRESPONSE_H
