// Generated by gencpp from file mavros_msgs/GeofencePullResponse.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_GEOFENCEPULLRESPONSE_H
#define MAVROS_MSGS_MESSAGE_GEOFENCEPULLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavros_msgs
{
template <class ContainerAllocator>
struct GeofencePullResponse_
{
  typedef GeofencePullResponse_<ContainerAllocator> Type;

  GeofencePullResponse_()
    : success(false)
    , count(0)
    , lat()
    , lng()  {
    }
  GeofencePullResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , count(0)
    , lat(_alloc)
    , lng(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef uint8_t _count_type;
  _count_type count;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _lat_type;
  _lat_type lat;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _lng_type;
  _lng_type lng;





  typedef boost::shared_ptr< ::mavros_msgs::GeofencePullResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavros_msgs::GeofencePullResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GeofencePullResponse_

typedef ::mavros_msgs::GeofencePullResponse_<std::allocator<void> > GeofencePullResponse;

typedef boost::shared_ptr< ::mavros_msgs::GeofencePullResponse > GeofencePullResponsePtr;
typedef boost::shared_ptr< ::mavros_msgs::GeofencePullResponse const> GeofencePullResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavros_msgs::GeofencePullResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavros_msgs::GeofencePullResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mavros_msgs': ['/home/flytpod/flytos/src/flytOS/flyt_core/core_nodes/mavros/mavros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::GeofencePullResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::GeofencePullResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::GeofencePullResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::GeofencePullResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::GeofencePullResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::GeofencePullResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavros_msgs::GeofencePullResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de057806094fca5534c26aac204ab4b9";
  }

  static const char* value(const ::mavros_msgs::GeofencePullResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xde057806094fca55ULL;
  static const uint64_t static_value2 = 0x34c26aac204ab4b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavros_msgs::GeofencePullResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavros_msgs/GeofencePullResponse";
  }

  static const char* value(const ::mavros_msgs::GeofencePullResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavros_msgs::GeofencePullResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
uint8 count\n\
float64[] lat\n\
float64[] lng\n\
";
  }

  static const char* value(const ::mavros_msgs::GeofencePullResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavros_msgs::GeofencePullResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.count);
      stream.next(m.lat);
      stream.next(m.lng);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GeofencePullResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavros_msgs::GeofencePullResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavros_msgs::GeofencePullResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "count: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.count);
    s << indent << "lat[]" << std::endl;
    for (size_t i = 0; i < v.lat.size(); ++i)
    {
      s << indent << "  lat[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.lat[i]);
    }
    s << indent << "lng[]" << std::endl;
    for (size_t i = 0; i < v.lng.size(); ++i)
    {
      s << indent << "  lng[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.lng[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_GEOFENCEPULLRESPONSE_H
