// Generated by gencpp from file mavros_msgs/LogEndReq.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_LOGENDREQ_H
#define MAVROS_MSGS_MESSAGE_LOGENDREQ_H

#include <ros/service_traits.h>


#include <mavros_msgs/LogEndReqRequest.h>
#include <mavros_msgs/LogEndReqResponse.h>


namespace mavros_msgs
{

struct LogEndReq
{

typedef LogEndReqRequest Request;
typedef LogEndReqResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LogEndReq
} // namespace mavros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros_msgs::LogEndReq > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::mavros_msgs::LogEndReq&) { return value(); }
};

template<>
struct DataType< ::mavros_msgs::LogEndReq > {
  static const char* value()
  {
    return "mavros_msgs/LogEndReq";
  }

  static const char* value(const ::mavros_msgs::LogEndReq&) { return value(); }
};


// service_traits::MD5Sum< ::mavros_msgs::LogEndReqRequest> should match 
// service_traits::MD5Sum< ::mavros_msgs::LogEndReq > 
template<>
struct MD5Sum< ::mavros_msgs::LogEndReqRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::LogEndReq >::value();
  }
  static const char* value(const ::mavros_msgs::LogEndReqRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::LogEndReqRequest> should match 
// service_traits::DataType< ::mavros_msgs::LogEndReq > 
template<>
struct DataType< ::mavros_msgs::LogEndReqRequest>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::LogEndReq >::value();
  }
  static const char* value(const ::mavros_msgs::LogEndReqRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros_msgs::LogEndReqResponse> should match 
// service_traits::MD5Sum< ::mavros_msgs::LogEndReq > 
template<>
struct MD5Sum< ::mavros_msgs::LogEndReqResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::LogEndReq >::value();
  }
  static const char* value(const ::mavros_msgs::LogEndReqResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::LogEndReqResponse> should match 
// service_traits::DataType< ::mavros_msgs::LogEndReq > 
template<>
struct DataType< ::mavros_msgs::LogEndReqResponse>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::LogEndReq >::value();
  }
  static const char* value(const ::mavros_msgs::LogEndReqResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_LOGENDREQ_H
