// Generated by gencpp from file mavros_msgs/LogListReq.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_LOGLISTREQ_H
#define MAVROS_MSGS_MESSAGE_LOGLISTREQ_H

#include <ros/service_traits.h>


#include <mavros_msgs/LogListReqRequest.h>
#include <mavros_msgs/LogListReqResponse.h>


namespace mavros_msgs
{

struct LogListReq
{

typedef LogListReqRequest Request;
typedef LogListReqResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LogListReq
} // namespace mavros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros_msgs::LogListReq > {
  static const char* value()
  {
    return "6364c880a0085320615fba1995407d03";
  }

  static const char* value(const ::mavros_msgs::LogListReq&) { return value(); }
};

template<>
struct DataType< ::mavros_msgs::LogListReq > {
  static const char* value()
  {
    return "mavros_msgs/LogListReq";
  }

  static const char* value(const ::mavros_msgs::LogListReq&) { return value(); }
};


// service_traits::MD5Sum< ::mavros_msgs::LogListReqRequest> should match 
// service_traits::MD5Sum< ::mavros_msgs::LogListReq > 
template<>
struct MD5Sum< ::mavros_msgs::LogListReqRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::LogListReq >::value();
  }
  static const char* value(const ::mavros_msgs::LogListReqRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::LogListReqRequest> should match 
// service_traits::DataType< ::mavros_msgs::LogListReq > 
template<>
struct DataType< ::mavros_msgs::LogListReqRequest>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::LogListReq >::value();
  }
  static const char* value(const ::mavros_msgs::LogListReqRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros_msgs::LogListReqResponse> should match 
// service_traits::MD5Sum< ::mavros_msgs::LogListReq > 
template<>
struct MD5Sum< ::mavros_msgs::LogListReqResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::LogListReq >::value();
  }
  static const char* value(const ::mavros_msgs::LogListReqResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::LogListReqResponse> should match 
// service_traits::DataType< ::mavros_msgs::LogListReq > 
template<>
struct DataType< ::mavros_msgs::LogListReqResponse>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::LogListReq >::value();
  }
  static const char* value(const ::mavros_msgs::LogListReqResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_LOGLISTREQ_H
