// Generated by gencpp from file mavros_msgs/VisionPoseDelta.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_VISIONPOSEDELTA_H
#define MAVROS_MSGS_MESSAGE_VISIONPOSEDELTA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mavros_msgs
{
template <class ContainerAllocator>
struct VisionPoseDelta_
{
  typedef VisionPoseDelta_<ContainerAllocator> Type;

  VisionPoseDelta_()
    : header()
    , time_delta_us(0)
    , angle_delta_roll(0.0)
    , angle_delta_pitch(0.0)
    , angle_delta_yaw(0.0)
    , position_delta_x(0.0)
    , position_delta_y(0.0)
    , position_delta_z(0.0)
    , confidence(0)  {
    }
  VisionPoseDelta_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , time_delta_us(0)
    , angle_delta_roll(0.0)
    , angle_delta_pitch(0.0)
    , angle_delta_yaw(0.0)
    , position_delta_x(0.0)
    , position_delta_y(0.0)
    , position_delta_z(0.0)
    , confidence(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _time_delta_us_type;
  _time_delta_us_type time_delta_us;

   typedef float _angle_delta_roll_type;
  _angle_delta_roll_type angle_delta_roll;

   typedef float _angle_delta_pitch_type;
  _angle_delta_pitch_type angle_delta_pitch;

   typedef float _angle_delta_yaw_type;
  _angle_delta_yaw_type angle_delta_yaw;

   typedef float _position_delta_x_type;
  _position_delta_x_type position_delta_x;

   typedef float _position_delta_y_type;
  _position_delta_y_type position_delta_y;

   typedef float _position_delta_z_type;
  _position_delta_z_type position_delta_z;

   typedef uint8_t _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::mavros_msgs::VisionPoseDelta_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavros_msgs::VisionPoseDelta_<ContainerAllocator> const> ConstPtr;

}; // struct VisionPoseDelta_

typedef ::mavros_msgs::VisionPoseDelta_<std::allocator<void> > VisionPoseDelta;

typedef boost::shared_ptr< ::mavros_msgs::VisionPoseDelta > VisionPoseDeltaPtr;
typedef boost::shared_ptr< ::mavros_msgs::VisionPoseDelta const> VisionPoseDeltaConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavros_msgs::VisionPoseDelta_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavros_msgs::VisionPoseDelta_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mavros_msgs': ['/home/flytpod/flytos/src/flytOS/flyt_core/core_nodes/mavros/mavros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::VisionPoseDelta_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::VisionPoseDelta_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::VisionPoseDelta_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::VisionPoseDelta_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::VisionPoseDelta_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::VisionPoseDelta_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavros_msgs::VisionPoseDelta_<ContainerAllocator> >
{
  static const char* value()
  {
    return "19f289602e4e368ce290900eecb3f779";
  }

  static const char* value(const ::mavros_msgs::VisionPoseDelta_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x19f289602e4e368cULL;
  static const uint64_t static_value2 = 0xe290900eecb3f779ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavros_msgs::VisionPoseDelta_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavros_msgs/VisionPoseDelta";
  }

  static const char* value(const ::mavros_msgs::VisionPoseDelta_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavros_msgs::VisionPoseDelta_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# VISION_POSITION_DELTA message data\n\
\n\
std_msgs/Header header\n\
\n\
uint32 time_delta_us\n\
\n\
float32 angle_delta_roll\n\
float32 angle_delta_pitch\n\
float32 angle_delta_yaw\n\
float32 position_delta_x\n\
float32 position_delta_y\n\
float32 position_delta_z\n\
\n\
uint8 confidence\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::mavros_msgs::VisionPoseDelta_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavros_msgs::VisionPoseDelta_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.time_delta_us);
      stream.next(m.angle_delta_roll);
      stream.next(m.angle_delta_pitch);
      stream.next(m.angle_delta_yaw);
      stream.next(m.position_delta_x);
      stream.next(m.position_delta_y);
      stream.next(m.position_delta_z);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VisionPoseDelta_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavros_msgs::VisionPoseDelta_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavros_msgs::VisionPoseDelta_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "time_delta_us: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.time_delta_us);
    s << indent << "angle_delta_roll: ";
    Printer<float>::stream(s, indent + "  ", v.angle_delta_roll);
    s << indent << "angle_delta_pitch: ";
    Printer<float>::stream(s, indent + "  ", v.angle_delta_pitch);
    s << indent << "angle_delta_yaw: ";
    Printer<float>::stream(s, indent + "  ", v.angle_delta_yaw);
    s << indent << "position_delta_x: ";
    Printer<float>::stream(s, indent + "  ", v.position_delta_x);
    s << indent << "position_delta_y: ";
    Printer<float>::stream(s, indent + "  ", v.position_delta_y);
    s << indent << "position_delta_z: ";
    Printer<float>::stream(s, indent + "  ", v.position_delta_z);
    s << indent << "confidence: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_VISIONPOSEDELTA_H
