// Generated by gencpp from file flyt_ms/DevSrvRequest.msg
// DO NOT EDIT!


#ifndef FLYT_MS_MESSAGE_DEVSRVREQUEST_H
#define FLYT_MS_MESSAGE_DEVSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace flyt_ms
{
template <class ContainerAllocator>
struct DevSrvRequest_
{
  typedef DevSrvRequest_<ContainerAllocator> Type;

  DevSrvRequest_()
    {
    }
  DevSrvRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::flyt_ms::DevSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flyt_ms::DevSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DevSrvRequest_

typedef ::flyt_ms::DevSrvRequest_<std::allocator<void> > DevSrvRequest;

typedef boost::shared_ptr< ::flyt_ms::DevSrvRequest > DevSrvRequestPtr;
typedef boost::shared_ptr< ::flyt_ms::DevSrvRequest const> DevSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flyt_ms::DevSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flyt_ms::DevSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace flyt_ms

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::flyt_ms::DevSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flyt_ms::DevSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flyt_ms::DevSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flyt_ms::DevSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flyt_ms::DevSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flyt_ms::DevSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flyt_ms::DevSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::flyt_ms::DevSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::flyt_ms::DevSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flyt_ms/DevSrvRequest";
  }

  static const char* value(const ::flyt_ms::DevSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flyt_ms::DevSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::flyt_ms::DevSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flyt_ms::DevSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DevSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flyt_ms::DevSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::flyt_ms::DevSrvRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FLYT_MS_MESSAGE_DEVSRVREQUEST_H
