// Generated by gencpp from file flyt_ms/LicChkSrvResponse.msg
// DO NOT EDIT!


#ifndef FLYT_MS_MESSAGE_LICCHKSRVRESPONSE_H
#define FLYT_MS_MESSAGE_LICCHKSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace flyt_ms
{
template <class ContainerAllocator>
struct LicChkSrvResponse_
{
  typedef LicChkSrvResponse_<ContainerAllocator> Type;

  LicChkSrvResponse_()
    : lic_type()
    , lic_valid(false)  {
    }
  LicChkSrvResponse_(const ContainerAllocator& _alloc)
    : lic_type(_alloc)
    , lic_valid(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _lic_type_type;
  _lic_type_type lic_type;

   typedef uint8_t _lic_valid_type;
  _lic_valid_type lic_valid;





  typedef boost::shared_ptr< ::flyt_ms::LicChkSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flyt_ms::LicChkSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LicChkSrvResponse_

typedef ::flyt_ms::LicChkSrvResponse_<std::allocator<void> > LicChkSrvResponse;

typedef boost::shared_ptr< ::flyt_ms::LicChkSrvResponse > LicChkSrvResponsePtr;
typedef boost::shared_ptr< ::flyt_ms::LicChkSrvResponse const> LicChkSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flyt_ms::LicChkSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flyt_ms::LicChkSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace flyt_ms

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::flyt_ms::LicChkSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flyt_ms::LicChkSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flyt_ms::LicChkSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flyt_ms::LicChkSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flyt_ms::LicChkSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flyt_ms::LicChkSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flyt_ms::LicChkSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "654af7e147b2d29af49c77584bd33b70";
  }

  static const char* value(const ::flyt_ms::LicChkSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x654af7e147b2d29aULL;
  static const uint64_t static_value2 = 0xf49c77584bd33b70ULL;
};

template<class ContainerAllocator>
struct DataType< ::flyt_ms::LicChkSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flyt_ms/LicChkSrvResponse";
  }

  static const char* value(const ::flyt_ms::LicChkSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flyt_ms::LicChkSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string lic_type\n\
bool lic_valid\n\
";
  }

  static const char* value(const ::flyt_ms::LicChkSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flyt_ms::LicChkSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lic_type);
      stream.next(m.lic_valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LicChkSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flyt_ms::LicChkSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flyt_ms::LicChkSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "lic_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.lic_type);
    s << indent << "lic_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lic_valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLYT_MS_MESSAGE_LICCHKSRVRESPONSE_H
