// Generated by gencpp from file flyt_ms/LicSrvResponse.msg
// DO NOT EDIT!


#ifndef FLYT_MS_MESSAGE_LICSRVRESPONSE_H
#define FLYT_MS_MESSAGE_LICSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace flyt_ms
{
template <class ContainerAllocator>
struct LicSrvResponse_
{
  typedef LicSrvResponse_<ContainerAllocator> Type;

  LicSrvResponse_()
    : lic_type()
    , exp_date()  {
    }
  LicSrvResponse_(const ContainerAllocator& _alloc)
    : lic_type(_alloc)
    , exp_date(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _lic_type_type;
  _lic_type_type lic_type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _exp_date_type;
  _exp_date_type exp_date;





  typedef boost::shared_ptr< ::flyt_ms::LicSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flyt_ms::LicSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LicSrvResponse_

typedef ::flyt_ms::LicSrvResponse_<std::allocator<void> > LicSrvResponse;

typedef boost::shared_ptr< ::flyt_ms::LicSrvResponse > LicSrvResponsePtr;
typedef boost::shared_ptr< ::flyt_ms::LicSrvResponse const> LicSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flyt_ms::LicSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flyt_ms::LicSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace flyt_ms

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::flyt_ms::LicSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flyt_ms::LicSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flyt_ms::LicSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flyt_ms::LicSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flyt_ms::LicSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flyt_ms::LicSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flyt_ms::LicSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2aa83faaac1ac420a3ff880e71ac394a";
  }

  static const char* value(const ::flyt_ms::LicSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2aa83faaac1ac420ULL;
  static const uint64_t static_value2 = 0xa3ff880e71ac394aULL;
};

template<class ContainerAllocator>
struct DataType< ::flyt_ms::LicSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flyt_ms/LicSrvResponse";
  }

  static const char* value(const ::flyt_ms::LicSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flyt_ms::LicSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string lic_type\n\
string exp_date\n\
\n\
";
  }

  static const char* value(const ::flyt_ms::LicSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flyt_ms::LicSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lic_type);
      stream.next(m.exp_date);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LicSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flyt_ms::LicSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flyt_ms::LicSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "lic_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.lic_type);
    s << indent << "exp_date: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.exp_date);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLYT_MS_MESSAGE_LICSRVRESPONSE_H
