// Generated by gencpp from file core_api/ActuatorTestingRequest.msg
// DO NOT EDIT!


#ifndef CORE_API_MESSAGE_ACTUATORTESTINGREQUEST_H
#define CORE_API_MESSAGE_ACTUATORTESTINGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace core_api
{
template <class ContainerAllocator>
struct ActuatorTestingRequest_
{
  typedef ActuatorTestingRequest_<ContainerAllocator> Type;

  ActuatorTestingRequest_()
    : actuator_id(0)
    , time_s(0.0)  {
    }
  ActuatorTestingRequest_(const ContainerAllocator& _alloc)
    : actuator_id(0)
    , time_s(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _actuator_id_type;
  _actuator_id_type actuator_id;

   typedef float _time_s_type;
  _time_s_type time_s;





  typedef boost::shared_ptr< ::core_api::ActuatorTestingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::core_api::ActuatorTestingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ActuatorTestingRequest_

typedef ::core_api::ActuatorTestingRequest_<std::allocator<void> > ActuatorTestingRequest;

typedef boost::shared_ptr< ::core_api::ActuatorTestingRequest > ActuatorTestingRequestPtr;
typedef boost::shared_ptr< ::core_api::ActuatorTestingRequest const> ActuatorTestingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::core_api::ActuatorTestingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::core_api::ActuatorTestingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace core_api

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'core_api': ['/home/flytpod/flytos/src/flytOS/flyt_core/core_api/core_api/msg/param', '/home/flytpod/flytos/src/flytOS/flyt_core/core_api/core_api/msg/param'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'diagnostic_msgs': ['/opt/ros/kinetic/share/diagnostic_msgs/cmake/../msg'], 'mavros_msgs': ['/home/flytpod/flytos/src/flytOS/flyt_core/core_nodes/mavros/mavros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::core_api::ActuatorTestingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::core_api::ActuatorTestingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::core_api::ActuatorTestingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::core_api::ActuatorTestingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::core_api::ActuatorTestingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::core_api::ActuatorTestingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::core_api::ActuatorTestingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c59cf021860f740acd550ade3646ebef";
  }

  static const char* value(const ::core_api::ActuatorTestingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc59cf021860f740aULL;
  static const uint64_t static_value2 = 0xcd550ade3646ebefULL;
};

template<class ContainerAllocator>
struct DataType< ::core_api::ActuatorTestingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "core_api/ActuatorTestingRequest";
  }

  static const char* value(const ::core_api::ActuatorTestingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::core_api::ActuatorTestingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 actuator_id\n\
float32 time_s\n\
";
  }

  static const char* value(const ::core_api::ActuatorTestingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::core_api::ActuatorTestingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.actuator_id);
      stream.next(m.time_s);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActuatorTestingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::core_api::ActuatorTestingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::core_api::ActuatorTestingRequest_<ContainerAllocator>& v)
  {
    s << indent << "actuator_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.actuator_id);
    s << indent << "time_s: ";
    Printer<float>::stream(s, indent + "  ", v.time_s);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CORE_API_MESSAGE_ACTUATORTESTINGREQUEST_H
