// Generated by gencpp from file core_api/AutopilotReboot.msg
// DO NOT EDIT!


#ifndef CORE_API_MESSAGE_AUTOPILOTREBOOT_H
#define CORE_API_MESSAGE_AUTOPILOTREBOOT_H

#include <ros/service_traits.h>


#include <core_api/AutopilotRebootRequest.h>
#include <core_api/AutopilotRebootResponse.h>


namespace core_api
{

struct AutopilotReboot
{

typedef AutopilotRebootRequest Request;
typedef AutopilotRebootResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AutopilotReboot
} // namespace core_api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::core_api::AutopilotReboot > {
  static const char* value()
  {
    return "fc3bd1e818efe2a00584996f3753a5c9";
  }

  static const char* value(const ::core_api::AutopilotReboot&) { return value(); }
};

template<>
struct DataType< ::core_api::AutopilotReboot > {
  static const char* value()
  {
    return "core_api/AutopilotReboot";
  }

  static const char* value(const ::core_api::AutopilotReboot&) { return value(); }
};


// service_traits::MD5Sum< ::core_api::AutopilotRebootRequest> should match 
// service_traits::MD5Sum< ::core_api::AutopilotReboot > 
template<>
struct MD5Sum< ::core_api::AutopilotRebootRequest>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::AutopilotReboot >::value();
  }
  static const char* value(const ::core_api::AutopilotRebootRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::AutopilotRebootRequest> should match 
// service_traits::DataType< ::core_api::AutopilotReboot > 
template<>
struct DataType< ::core_api::AutopilotRebootRequest>
{
  static const char* value()
  {
    return DataType< ::core_api::AutopilotReboot >::value();
  }
  static const char* value(const ::core_api::AutopilotRebootRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::core_api::AutopilotRebootResponse> should match 
// service_traits::MD5Sum< ::core_api::AutopilotReboot > 
template<>
struct MD5Sum< ::core_api::AutopilotRebootResponse>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::AutopilotReboot >::value();
  }
  static const char* value(const ::core_api::AutopilotRebootResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::AutopilotRebootResponse> should match 
// service_traits::DataType< ::core_api::AutopilotReboot > 
template<>
struct DataType< ::core_api::AutopilotRebootResponse>
{
  static const char* value()
  {
    return DataType< ::core_api::AutopilotReboot >::value();
  }
  static const char* value(const ::core_api::AutopilotRebootResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CORE_API_MESSAGE_AUTOPILOTREBOOT_H
