// Generated by gencpp from file core_api/Disarm.msg
// DO NOT EDIT!


#ifndef CORE_API_MESSAGE_DISARM_H
#define CORE_API_MESSAGE_DISARM_H

#include <ros/service_traits.h>


#include <core_api/DisarmRequest.h>
#include <core_api/DisarmResponse.h>


namespace core_api
{

struct Disarm
{

typedef DisarmRequest Request;
typedef DisarmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Disarm
} // namespace core_api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::core_api::Disarm > {
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::core_api::Disarm&) { return value(); }
};

template<>
struct DataType< ::core_api::Disarm > {
  static const char* value()
  {
    return "core_api/Disarm";
  }

  static const char* value(const ::core_api::Disarm&) { return value(); }
};


// service_traits::MD5Sum< ::core_api::DisarmRequest> should match 
// service_traits::MD5Sum< ::core_api::Disarm > 
template<>
struct MD5Sum< ::core_api::DisarmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::Disarm >::value();
  }
  static const char* value(const ::core_api::DisarmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::DisarmRequest> should match 
// service_traits::DataType< ::core_api::Disarm > 
template<>
struct DataType< ::core_api::DisarmRequest>
{
  static const char* value()
  {
    return DataType< ::core_api::Disarm >::value();
  }
  static const char* value(const ::core_api::DisarmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::core_api::DisarmResponse> should match 
// service_traits::MD5Sum< ::core_api::Disarm > 
template<>
struct MD5Sum< ::core_api::DisarmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::Disarm >::value();
  }
  static const char* value(const ::core_api::DisarmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::DisarmResponse> should match 
// service_traits::DataType< ::core_api::Disarm > 
template<>
struct DataType< ::core_api::DisarmResponse>
{
  static const char* value()
  {
    return DataType< ::core_api::Disarm >::value();
  }
  static const char* value(const ::core_api::DisarmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CORE_API_MESSAGE_DISARM_H
