// Generated by gencpp from file core_api/ExecScript.msg
// DO NOT EDIT!


#ifndef CORE_API_MESSAGE_EXECSCRIPT_H
#define CORE_API_MESSAGE_EXECSCRIPT_H

#include <ros/service_traits.h>


#include <core_api/ExecScriptRequest.h>
#include <core_api/ExecScriptResponse.h>


namespace core_api
{

struct ExecScript
{

typedef ExecScriptRequest Request;
typedef ExecScriptResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExecScript
} // namespace core_api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::core_api::ExecScript > {
  static const char* value()
  {
    return "dc0ad6b67076c8affab5d27840600a3e";
  }

  static const char* value(const ::core_api::ExecScript&) { return value(); }
};

template<>
struct DataType< ::core_api::ExecScript > {
  static const char* value()
  {
    return "core_api/ExecScript";
  }

  static const char* value(const ::core_api::ExecScript&) { return value(); }
};


// service_traits::MD5Sum< ::core_api::ExecScriptRequest> should match 
// service_traits::MD5Sum< ::core_api::ExecScript > 
template<>
struct MD5Sum< ::core_api::ExecScriptRequest>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::ExecScript >::value();
  }
  static const char* value(const ::core_api::ExecScriptRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::ExecScriptRequest> should match 
// service_traits::DataType< ::core_api::ExecScript > 
template<>
struct DataType< ::core_api::ExecScriptRequest>
{
  static const char* value()
  {
    return DataType< ::core_api::ExecScript >::value();
  }
  static const char* value(const ::core_api::ExecScriptRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::core_api::ExecScriptResponse> should match 
// service_traits::MD5Sum< ::core_api::ExecScript > 
template<>
struct MD5Sum< ::core_api::ExecScriptResponse>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::ExecScript >::value();
  }
  static const char* value(const ::core_api::ExecScriptResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::ExecScriptResponse> should match 
// service_traits::DataType< ::core_api::ExecScript > 
template<>
struct DataType< ::core_api::ExecScriptResponse>
{
  static const char* value()
  {
    return DataType< ::core_api::ExecScript >::value();
  }
  static const char* value(const ::core_api::ExecScriptResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CORE_API_MESSAGE_EXECSCRIPT_H
