// Generated by gencpp from file core_api/GimbalConfigureRequest.msg
// DO NOT EDIT!


#ifndef CORE_API_MESSAGE_GIMBALCONFIGUREREQUEST_H
#define CORE_API_MESSAGE_GIMBALCONFIGUREREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace core_api
{
template <class ContainerAllocator>
struct GimbalConfigureRequest_
{
  typedef GimbalConfigureRequest_<ContainerAllocator> Type;

  GimbalConfigureRequest_()
    : do_roll_compensation(false)
    , do_pitch_compensation(false)
    , do_yaw_compensation(false)  {
    }
  GimbalConfigureRequest_(const ContainerAllocator& _alloc)
    : do_roll_compensation(false)
    , do_pitch_compensation(false)
    , do_yaw_compensation(false)  {
  (void)_alloc;
    }



   typedef uint8_t _do_roll_compensation_type;
  _do_roll_compensation_type do_roll_compensation;

   typedef uint8_t _do_pitch_compensation_type;
  _do_pitch_compensation_type do_pitch_compensation;

   typedef uint8_t _do_yaw_compensation_type;
  _do_yaw_compensation_type do_yaw_compensation;





  typedef boost::shared_ptr< ::core_api::GimbalConfigureRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::core_api::GimbalConfigureRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GimbalConfigureRequest_

typedef ::core_api::GimbalConfigureRequest_<std::allocator<void> > GimbalConfigureRequest;

typedef boost::shared_ptr< ::core_api::GimbalConfigureRequest > GimbalConfigureRequestPtr;
typedef boost::shared_ptr< ::core_api::GimbalConfigureRequest const> GimbalConfigureRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::core_api::GimbalConfigureRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::core_api::GimbalConfigureRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace core_api

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'core_api': ['/home/flytpod/flytos/src/flytOS/flyt_core/core_api/core_api/msg/param', '/home/flytpod/flytos/src/flytOS/flyt_core/core_api/core_api/msg/param'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'diagnostic_msgs': ['/opt/ros/kinetic/share/diagnostic_msgs/cmake/../msg'], 'mavros_msgs': ['/home/flytpod/flytos/src/flytOS/flyt_core/core_nodes/mavros/mavros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::core_api::GimbalConfigureRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::core_api::GimbalConfigureRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::core_api::GimbalConfigureRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::core_api::GimbalConfigureRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::core_api::GimbalConfigureRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::core_api::GimbalConfigureRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::core_api::GimbalConfigureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ccfc17345b70c57fcf5df62c1c093997";
  }

  static const char* value(const ::core_api::GimbalConfigureRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xccfc17345b70c57fULL;
  static const uint64_t static_value2 = 0xcf5df62c1c093997ULL;
};

template<class ContainerAllocator>
struct DataType< ::core_api::GimbalConfigureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "core_api/GimbalConfigureRequest";
  }

  static const char* value(const ::core_api::GimbalConfigureRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::core_api::GimbalConfigureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
bool do_roll_compensation\n\
bool do_pitch_compensation\n\
bool do_yaw_compensation\n\
\n\
";
  }

  static const char* value(const ::core_api::GimbalConfigureRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::core_api::GimbalConfigureRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.do_roll_compensation);
      stream.next(m.do_pitch_compensation);
      stream.next(m.do_yaw_compensation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GimbalConfigureRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::core_api::GimbalConfigureRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::core_api::GimbalConfigureRequest_<ContainerAllocator>& v)
  {
    s << indent << "do_roll_compensation: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.do_roll_compensation);
    s << indent << "do_pitch_compensation: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.do_pitch_compensation);
    s << indent << "do_yaw_compensation: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.do_yaw_compensation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CORE_API_MESSAGE_GIMBALCONFIGUREREQUEST_H
