// Generated by gencpp from file core_api/IsPkgActivated.msg
// DO NOT EDIT!


#ifndef CORE_API_MESSAGE_ISPKGACTIVATED_H
#define CORE_API_MESSAGE_ISPKGACTIVATED_H

#include <ros/service_traits.h>


#include <core_api/IsPkgActivatedRequest.h>
#include <core_api/IsPkgActivatedResponse.h>


namespace core_api
{

struct IsPkgActivated
{

typedef IsPkgActivatedRequest Request;
typedef IsPkgActivatedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IsPkgActivated
} // namespace core_api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::core_api::IsPkgActivated > {
  static const char* value()
  {
    return "840df30bd3d88303e2027160e9982454";
  }

  static const char* value(const ::core_api::IsPkgActivated&) { return value(); }
};

template<>
struct DataType< ::core_api::IsPkgActivated > {
  static const char* value()
  {
    return "core_api/IsPkgActivated";
  }

  static const char* value(const ::core_api::IsPkgActivated&) { return value(); }
};


// service_traits::MD5Sum< ::core_api::IsPkgActivatedRequest> should match 
// service_traits::MD5Sum< ::core_api::IsPkgActivated > 
template<>
struct MD5Sum< ::core_api::IsPkgActivatedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::IsPkgActivated >::value();
  }
  static const char* value(const ::core_api::IsPkgActivatedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::IsPkgActivatedRequest> should match 
// service_traits::DataType< ::core_api::IsPkgActivated > 
template<>
struct DataType< ::core_api::IsPkgActivatedRequest>
{
  static const char* value()
  {
    return DataType< ::core_api::IsPkgActivated >::value();
  }
  static const char* value(const ::core_api::IsPkgActivatedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::core_api::IsPkgActivatedResponse> should match 
// service_traits::MD5Sum< ::core_api::IsPkgActivated > 
template<>
struct MD5Sum< ::core_api::IsPkgActivatedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::IsPkgActivated >::value();
  }
  static const char* value(const ::core_api::IsPkgActivatedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::IsPkgActivatedResponse> should match 
// service_traits::DataType< ::core_api::IsPkgActivated > 
template<>
struct DataType< ::core_api::IsPkgActivatedResponse>
{
  static const char* value()
  {
    return DataType< ::core_api::IsPkgActivated >::value();
  }
  static const char* value(const ::core_api::IsPkgActivatedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CORE_API_MESSAGE_ISPKGACTIVATED_H
