// Generated by gencpp from file core_api/ModuleCalibrationRequest.msg
// DO NOT EDIT!


#ifndef CORE_API_MESSAGE_MODULECALIBRATIONREQUEST_H
#define CORE_API_MESSAGE_MODULECALIBRATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace core_api
{
template <class ContainerAllocator>
struct ModuleCalibrationRequest_
{
  typedef ModuleCalibrationRequest_<ContainerAllocator> Type;

  ModuleCalibrationRequest_()
    : module_calibrate(0)  {
    }
  ModuleCalibrationRequest_(const ContainerAllocator& _alloc)
    : module_calibrate(0)  {
  (void)_alloc;
    }



   typedef int8_t _module_calibrate_type;
  _module_calibrate_type module_calibrate;



  enum {
    STOP = 0u,
    ACCELEROMETER = 1u,
    GYROSCOPE = 2u,
    MAGNETOMETER = 3u,
    RC = 4u,
    RC_TRIM = 5u,
    RC_STOP = 6u,
    LEVEL = 7u,
    AIRSPEED = 8u,
  };


  typedef boost::shared_ptr< ::core_api::ModuleCalibrationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::core_api::ModuleCalibrationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ModuleCalibrationRequest_

typedef ::core_api::ModuleCalibrationRequest_<std::allocator<void> > ModuleCalibrationRequest;

typedef boost::shared_ptr< ::core_api::ModuleCalibrationRequest > ModuleCalibrationRequestPtr;
typedef boost::shared_ptr< ::core_api::ModuleCalibrationRequest const> ModuleCalibrationRequestConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::core_api::ModuleCalibrationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::core_api::ModuleCalibrationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace core_api

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'core_api': ['/home/flytpod/flytos/src/flytOS/flyt_core/core_api/core_api/msg/param', '/home/flytpod/flytos/src/flytOS/flyt_core/core_api/core_api/msg/param'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'diagnostic_msgs': ['/opt/ros/kinetic/share/diagnostic_msgs/cmake/../msg'], 'mavros_msgs': ['/home/flytpod/flytos/src/flytOS/flyt_core/core_nodes/mavros/mavros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::core_api::ModuleCalibrationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::core_api::ModuleCalibrationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::core_api::ModuleCalibrationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::core_api::ModuleCalibrationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::core_api::ModuleCalibrationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::core_api::ModuleCalibrationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::core_api::ModuleCalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57b406498875fd11aa66dfdce74c7a0f";
  }

  static const char* value(const ::core_api::ModuleCalibrationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57b406498875fd11ULL;
  static const uint64_t static_value2 = 0xaa66dfdce74c7a0fULL;
};

template<class ContainerAllocator>
struct DataType< ::core_api::ModuleCalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "core_api/ModuleCalibrationRequest";
  }

  static const char* value(const ::core_api::ModuleCalibrationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::core_api::ModuleCalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 STOP = 0\n\
uint8 ACCELEROMETER = 1\n\
uint8 GYROSCOPE = 2\n\
uint8 MAGNETOMETER = 3\n\
uint8 RC = 4\n\
uint8 RC_TRIM = 5\n\
uint8 RC_STOP = 6\n\
uint8 LEVEL = 7\n\
uint8 AIRSPEED = 8\n\
\n\
int8 module_calibrate\n\
";
  }

  static const char* value(const ::core_api::ModuleCalibrationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::core_api::ModuleCalibrationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.module_calibrate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModuleCalibrationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::core_api::ModuleCalibrationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::core_api::ModuleCalibrationRequest_<ContainerAllocator>& v)
  {
    s << indent << "module_calibrate: ";
    Printer<int8_t>::stream(s, indent + "  ", v.module_calibrate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CORE_API_MESSAGE_MODULECALIBRATIONREQUEST_H
