// Generated by gencpp from file core_api/ParamGet.msg
// DO NOT EDIT!


#ifndef CORE_API_MESSAGE_PARAMGET_H
#define CORE_API_MESSAGE_PARAMGET_H

#include <ros/service_traits.h>


#include <core_api/ParamGetRequest.h>
#include <core_api/ParamGetResponse.h>


namespace core_api
{

struct ParamGet
{

typedef ParamGetRequest Request;
typedef ParamGetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ParamGet
} // namespace core_api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::core_api::ParamGet > {
  static const char* value()
  {
    return "ee3a46669de239e9ddb25d063c5e6029";
  }

  static const char* value(const ::core_api::ParamGet&) { return value(); }
};

template<>
struct DataType< ::core_api::ParamGet > {
  static const char* value()
  {
    return "core_api/ParamGet";
  }

  static const char* value(const ::core_api::ParamGet&) { return value(); }
};


// service_traits::MD5Sum< ::core_api::ParamGetRequest> should match 
// service_traits::MD5Sum< ::core_api::ParamGet > 
template<>
struct MD5Sum< ::core_api::ParamGetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::ParamGet >::value();
  }
  static const char* value(const ::core_api::ParamGetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::ParamGetRequest> should match 
// service_traits::DataType< ::core_api::ParamGet > 
template<>
struct DataType< ::core_api::ParamGetRequest>
{
  static const char* value()
  {
    return DataType< ::core_api::ParamGet >::value();
  }
  static const char* value(const ::core_api::ParamGetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::core_api::ParamGetResponse> should match 
// service_traits::MD5Sum< ::core_api::ParamGet > 
template<>
struct MD5Sum< ::core_api::ParamGetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::ParamGet >::value();
  }
  static const char* value(const ::core_api::ParamGetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::ParamGetResponse> should match 
// service_traits::DataType< ::core_api::ParamGet > 
template<>
struct DataType< ::core_api::ParamGetResponse>
{
  static const char* value()
  {
    return DataType< ::core_api::ParamGet >::value();
  }
  static const char* value(const ::core_api::ParamGetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CORE_API_MESSAGE_PARAMGET_H
