// Generated by gencpp from file core_api/ParamGetAll.msg
// DO NOT EDIT!


#ifndef CORE_API_MESSAGE_PARAMGETALL_H
#define CORE_API_MESSAGE_PARAMGETALL_H

#include <ros/service_traits.h>


#include <core_api/ParamGetAllRequest.h>
#include <core_api/ParamGetAllResponse.h>


namespace core_api
{

struct ParamGetAll
{

typedef ParamGetAllRequest Request;
typedef ParamGetAllResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ParamGetAll
} // namespace core_api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::core_api::ParamGetAll > {
  static const char* value()
  {
    return "b71ead203534a0f9bf45c0f7dcff82b8";
  }

  static const char* value(const ::core_api::ParamGetAll&) { return value(); }
};

template<>
struct DataType< ::core_api::ParamGetAll > {
  static const char* value()
  {
    return "core_api/ParamGetAll";
  }

  static const char* value(const ::core_api::ParamGetAll&) { return value(); }
};


// service_traits::MD5Sum< ::core_api::ParamGetAllRequest> should match 
// service_traits::MD5Sum< ::core_api::ParamGetAll > 
template<>
struct MD5Sum< ::core_api::ParamGetAllRequest>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::ParamGetAll >::value();
  }
  static const char* value(const ::core_api::ParamGetAllRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::ParamGetAllRequest> should match 
// service_traits::DataType< ::core_api::ParamGetAll > 
template<>
struct DataType< ::core_api::ParamGetAllRequest>
{
  static const char* value()
  {
    return DataType< ::core_api::ParamGetAll >::value();
  }
  static const char* value(const ::core_api::ParamGetAllRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::core_api::ParamGetAllResponse> should match 
// service_traits::MD5Sum< ::core_api::ParamGetAll > 
template<>
struct MD5Sum< ::core_api::ParamGetAllResponse>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::ParamGetAll >::value();
  }
  static const char* value(const ::core_api::ParamGetAllResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::ParamGetAllResponse> should match 
// service_traits::DataType< ::core_api::ParamGetAll > 
template<>
struct DataType< ::core_api::ParamGetAllResponse>
{
  static const char* value()
  {
    return DataType< ::core_api::ParamGetAll >::value();
  }
  static const char* value(const ::core_api::ParamGetAllResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CORE_API_MESSAGE_PARAMGETALL_H
