// Generated by gencpp from file core_api/ParamLoad.msg
// DO NOT EDIT!


#ifndef CORE_API_MESSAGE_PARAMLOAD_H
#define CORE_API_MESSAGE_PARAMLOAD_H

#include <ros/service_traits.h>


#include <core_api/ParamLoadRequest.h>
#include <core_api/ParamLoadResponse.h>


namespace core_api
{

struct ParamLoad
{

typedef ParamLoadRequest Request;
typedef ParamLoadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ParamLoad
} // namespace core_api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::core_api::ParamLoad > {
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::core_api::ParamLoad&) { return value(); }
};

template<>
struct DataType< ::core_api::ParamLoad > {
  static const char* value()
  {
    return "core_api/ParamLoad";
  }

  static const char* value(const ::core_api::ParamLoad&) { return value(); }
};


// service_traits::MD5Sum< ::core_api::ParamLoadRequest> should match 
// service_traits::MD5Sum< ::core_api::ParamLoad > 
template<>
struct MD5Sum< ::core_api::ParamLoadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::ParamLoad >::value();
  }
  static const char* value(const ::core_api::ParamLoadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::ParamLoadRequest> should match 
// service_traits::DataType< ::core_api::ParamLoad > 
template<>
struct DataType< ::core_api::ParamLoadRequest>
{
  static const char* value()
  {
    return DataType< ::core_api::ParamLoad >::value();
  }
  static const char* value(const ::core_api::ParamLoadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::core_api::ParamLoadResponse> should match 
// service_traits::MD5Sum< ::core_api::ParamLoad > 
template<>
struct MD5Sum< ::core_api::ParamLoadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::ParamLoad >::value();
  }
  static const char* value(const ::core_api::ParamLoadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::ParamLoadResponse> should match 
// service_traits::DataType< ::core_api::ParamLoad > 
template<>
struct DataType< ::core_api::ParamLoadResponse>
{
  static const char* value()
  {
    return DataType< ::core_api::ParamLoad >::value();
  }
  static const char* value(const ::core_api::ParamLoadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CORE_API_MESSAGE_PARAMLOAD_H
