// Generated by gencpp from file core_api/ParamSet.msg
// DO NOT EDIT!


#ifndef CORE_API_MESSAGE_PARAMSET_H
#define CORE_API_MESSAGE_PARAMSET_H

#include <ros/service_traits.h>


#include <core_api/ParamSetRequest.h>
#include <core_api/ParamSetResponse.h>


namespace core_api
{

struct ParamSet
{

typedef ParamSetRequest Request;
typedef ParamSetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ParamSet
} // namespace core_api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::core_api::ParamSet > {
  static const char* value()
  {
    return "3139407759ce2a5b88c5244e2a57e352";
  }

  static const char* value(const ::core_api::ParamSet&) { return value(); }
};

template<>
struct DataType< ::core_api::ParamSet > {
  static const char* value()
  {
    return "core_api/ParamSet";
  }

  static const char* value(const ::core_api::ParamSet&) { return value(); }
};


// service_traits::MD5Sum< ::core_api::ParamSetRequest> should match 
// service_traits::MD5Sum< ::core_api::ParamSet > 
template<>
struct MD5Sum< ::core_api::ParamSetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::ParamSet >::value();
  }
  static const char* value(const ::core_api::ParamSetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::ParamSetRequest> should match 
// service_traits::DataType< ::core_api::ParamSet > 
template<>
struct DataType< ::core_api::ParamSetRequest>
{
  static const char* value()
  {
    return DataType< ::core_api::ParamSet >::value();
  }
  static const char* value(const ::core_api::ParamSetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::core_api::ParamSetResponse> should match 
// service_traits::MD5Sum< ::core_api::ParamSet > 
template<>
struct MD5Sum< ::core_api::ParamSetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::ParamSet >::value();
  }
  static const char* value(const ::core_api::ParamSetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::ParamSetResponse> should match 
// service_traits::DataType< ::core_api::ParamSet > 
template<>
struct DataType< ::core_api::ParamSetResponse>
{
  static const char* value()
  {
    return DataType< ::core_api::ParamSet >::value();
  }
  static const char* value(const ::core_api::ParamSetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CORE_API_MESSAGE_PARAMSET_H
