// Generated by gencpp from file core_api/PositionSetGlobal.msg
// DO NOT EDIT!


#ifndef CORE_API_MESSAGE_POSITIONSETGLOBAL_H
#define CORE_API_MESSAGE_POSITIONSETGLOBAL_H

#include <ros/service_traits.h>


#include <core_api/PositionSetGlobalRequest.h>
#include <core_api/PositionSetGlobalResponse.h>


namespace core_api
{

struct PositionSetGlobal
{

typedef PositionSetGlobalRequest Request;
typedef PositionSetGlobalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PositionSetGlobal
} // namespace core_api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::core_api::PositionSetGlobal > {
  static const char* value()
  {
    return "6578c26fcd60d8ecd591fdca570571f8";
  }

  static const char* value(const ::core_api::PositionSetGlobal&) { return value(); }
};

template<>
struct DataType< ::core_api::PositionSetGlobal > {
  static const char* value()
  {
    return "core_api/PositionSetGlobal";
  }

  static const char* value(const ::core_api::PositionSetGlobal&) { return value(); }
};


// service_traits::MD5Sum< ::core_api::PositionSetGlobalRequest> should match 
// service_traits::MD5Sum< ::core_api::PositionSetGlobal > 
template<>
struct MD5Sum< ::core_api::PositionSetGlobalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::PositionSetGlobal >::value();
  }
  static const char* value(const ::core_api::PositionSetGlobalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::PositionSetGlobalRequest> should match 
// service_traits::DataType< ::core_api::PositionSetGlobal > 
template<>
struct DataType< ::core_api::PositionSetGlobalRequest>
{
  static const char* value()
  {
    return DataType< ::core_api::PositionSetGlobal >::value();
  }
  static const char* value(const ::core_api::PositionSetGlobalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::core_api::PositionSetGlobalResponse> should match 
// service_traits::MD5Sum< ::core_api::PositionSetGlobal > 
template<>
struct MD5Sum< ::core_api::PositionSetGlobalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::PositionSetGlobal >::value();
  }
  static const char* value(const ::core_api::PositionSetGlobalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::PositionSetGlobalResponse> should match 
// service_traits::DataType< ::core_api::PositionSetGlobal > 
template<>
struct DataType< ::core_api::PositionSetGlobalResponse>
{
  static const char* value()
  {
    return DataType< ::core_api::PositionSetGlobal >::value();
  }
  static const char* value(const ::core_api::PositionSetGlobalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CORE_API_MESSAGE_POSITIONSETGLOBAL_H
