// Generated by gencpp from file core_api/PositionSetGlobalRequest.msg
// DO NOT EDIT!


#ifndef CORE_API_MESSAGE_POSITIONSETGLOBALREQUEST_H
#define CORE_API_MESSAGE_POSITIONSETGLOBALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/TwistStamped.h>

namespace core_api
{
template <class ContainerAllocator>
struct PositionSetGlobalRequest_
{
  typedef PositionSetGlobalRequest_<ContainerAllocator> Type;

  PositionSetGlobalRequest_()
    : twist()
    , lat_x(0.0)
    , long_y(0.0)
    , rel_alt_z(0.0)
    , yaw(0.0)
    , tolerance(0.0)
    , async(false)
    , yaw_valid(false)  {
    }
  PositionSetGlobalRequest_(const ContainerAllocator& _alloc)
    : twist(_alloc)
    , lat_x(0.0)
    , long_y(0.0)
    , rel_alt_z(0.0)
    , yaw(0.0)
    , tolerance(0.0)
    , async(false)
    , yaw_valid(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::TwistStamped_<ContainerAllocator>  _twist_type;
  _twist_type twist;

   typedef float _lat_x_type;
  _lat_x_type lat_x;

   typedef float _long_y_type;
  _long_y_type long_y;

   typedef float _rel_alt_z_type;
  _rel_alt_z_type rel_alt_z;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _tolerance_type;
  _tolerance_type tolerance;

   typedef uint8_t _async_type;
  _async_type async;

   typedef uint8_t _yaw_valid_type;
  _yaw_valid_type yaw_valid;





  typedef boost::shared_ptr< ::core_api::PositionSetGlobalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::core_api::PositionSetGlobalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PositionSetGlobalRequest_

typedef ::core_api::PositionSetGlobalRequest_<std::allocator<void> > PositionSetGlobalRequest;

typedef boost::shared_ptr< ::core_api::PositionSetGlobalRequest > PositionSetGlobalRequestPtr;
typedef boost::shared_ptr< ::core_api::PositionSetGlobalRequest const> PositionSetGlobalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::core_api::PositionSetGlobalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::core_api::PositionSetGlobalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace core_api

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'core_api': ['/home/flytpod/flytos/src/flytOS/flyt_core/core_api/core_api/msg/param', '/home/flytpod/flytos/src/flytOS/flyt_core/core_api/core_api/msg/param'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'diagnostic_msgs': ['/opt/ros/kinetic/share/diagnostic_msgs/cmake/../msg'], 'mavros_msgs': ['/home/flytpod/flytos/src/flytOS/flyt_core/core_nodes/mavros/mavros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::core_api::PositionSetGlobalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::core_api::PositionSetGlobalRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::core_api::PositionSetGlobalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::core_api::PositionSetGlobalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::core_api::PositionSetGlobalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::core_api::PositionSetGlobalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::core_api::PositionSetGlobalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "16275473bd2aa16fd2f714ae721eb87d";
  }

  static const char* value(const ::core_api::PositionSetGlobalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x16275473bd2aa16fULL;
  static const uint64_t static_value2 = 0xd2f714ae721eb87dULL;
};

template<class ContainerAllocator>
struct DataType< ::core_api::PositionSetGlobalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "core_api/PositionSetGlobalRequest";
  }

  static const char* value(const ::core_api::PositionSetGlobalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::core_api::PositionSetGlobalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
\n\
geometry_msgs/TwistStamped twist\n\
float32 lat_x\n\
float32 long_y\n\
float32 rel_alt_z\n\
float32 yaw\n\
float32 tolerance\n\
bool async\n\
bool yaw_valid\n\
\n\
================================================================================\n\
MSG: geometry_msgs/TwistStamped\n\
# A twist with reference coordinate frame and timestamp\n\
Header header\n\
Twist twist\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::core_api::PositionSetGlobalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::core_api::PositionSetGlobalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.twist);
      stream.next(m.lat_x);
      stream.next(m.long_y);
      stream.next(m.rel_alt_z);
      stream.next(m.yaw);
      stream.next(m.tolerance);
      stream.next(m.async);
      stream.next(m.yaw_valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionSetGlobalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::core_api::PositionSetGlobalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::core_api::PositionSetGlobalRequest_<ContainerAllocator>& v)
  {
    s << indent << "twist: ";
    s << std::endl;
    Printer< ::geometry_msgs::TwistStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.twist);
    s << indent << "lat_x: ";
    Printer<float>::stream(s, indent + "  ", v.lat_x);
    s << indent << "long_y: ";
    Printer<float>::stream(s, indent + "  ", v.long_y);
    s << indent << "rel_alt_z: ";
    Printer<float>::stream(s, indent + "  ", v.rel_alt_z);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "tolerance: ";
    Printer<float>::stream(s, indent + "  ", v.tolerance);
    s << indent << "async: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.async);
    s << indent << "yaw_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.yaw_valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CORE_API_MESSAGE_POSITIONSETGLOBALREQUEST_H
