// Generated by gencpp from file core_api/ServoControl.msg
// DO NOT EDIT!


#ifndef CORE_API_MESSAGE_SERVOCONTROL_H
#define CORE_API_MESSAGE_SERVOCONTROL_H

#include <ros/service_traits.h>


#include <core_api/ServoControlRequest.h>
#include <core_api/ServoControlResponse.h>


namespace core_api
{

struct ServoControl
{

typedef ServoControlRequest Request;
typedef ServoControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServoControl
} // namespace core_api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::core_api::ServoControl > {
  static const char* value()
  {
    return "ad786bcadcc1dd8887302facb8d1cbdd";
  }

  static const char* value(const ::core_api::ServoControl&) { return value(); }
};

template<>
struct DataType< ::core_api::ServoControl > {
  static const char* value()
  {
    return "core_api/ServoControl";
  }

  static const char* value(const ::core_api::ServoControl&) { return value(); }
};


// service_traits::MD5Sum< ::core_api::ServoControlRequest> should match 
// service_traits::MD5Sum< ::core_api::ServoControl > 
template<>
struct MD5Sum< ::core_api::ServoControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::ServoControl >::value();
  }
  static const char* value(const ::core_api::ServoControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::ServoControlRequest> should match 
// service_traits::DataType< ::core_api::ServoControl > 
template<>
struct DataType< ::core_api::ServoControlRequest>
{
  static const char* value()
  {
    return DataType< ::core_api::ServoControl >::value();
  }
  static const char* value(const ::core_api::ServoControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::core_api::ServoControlResponse> should match 
// service_traits::MD5Sum< ::core_api::ServoControl > 
template<>
struct MD5Sum< ::core_api::ServoControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::ServoControl >::value();
  }
  static const char* value(const ::core_api::ServoControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::ServoControlResponse> should match 
// service_traits::DataType< ::core_api::ServoControl > 
template<>
struct DataType< ::core_api::ServoControlResponse>
{
  static const char* value()
  {
    return DataType< ::core_api::ServoControl >::value();
  }
  static const char* value(const ::core_api::ServoControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CORE_API_MESSAGE_SERVOCONTROL_H
