// Generated by gencpp from file core_api/SetHome.msg
// DO NOT EDIT!


#ifndef CORE_API_MESSAGE_SETHOME_H
#define CORE_API_MESSAGE_SETHOME_H

#include <ros/service_traits.h>


#include <core_api/SetHomeRequest.h>
#include <core_api/SetHomeResponse.h>


namespace core_api
{

struct SetHome
{

typedef SetHomeRequest Request;
typedef SetHomeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetHome
} // namespace core_api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::core_api::SetHome > {
  static const char* value()
  {
    return "6fecffddcd142aa151250a5dd831cd59";
  }

  static const char* value(const ::core_api::SetHome&) { return value(); }
};

template<>
struct DataType< ::core_api::SetHome > {
  static const char* value()
  {
    return "core_api/SetHome";
  }

  static const char* value(const ::core_api::SetHome&) { return value(); }
};


// service_traits::MD5Sum< ::core_api::SetHomeRequest> should match 
// service_traits::MD5Sum< ::core_api::SetHome > 
template<>
struct MD5Sum< ::core_api::SetHomeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::SetHome >::value();
  }
  static const char* value(const ::core_api::SetHomeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::SetHomeRequest> should match 
// service_traits::DataType< ::core_api::SetHome > 
template<>
struct DataType< ::core_api::SetHomeRequest>
{
  static const char* value()
  {
    return DataType< ::core_api::SetHome >::value();
  }
  static const char* value(const ::core_api::SetHomeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::core_api::SetHomeResponse> should match 
// service_traits::MD5Sum< ::core_api::SetHome > 
template<>
struct MD5Sum< ::core_api::SetHomeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::SetHome >::value();
  }
  static const char* value(const ::core_api::SetHomeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::SetHomeResponse> should match 
// service_traits::DataType< ::core_api::SetHome > 
template<>
struct DataType< ::core_api::SetHomeResponse>
{
  static const char* value()
  {
    return DataType< ::core_api::SetHome >::value();
  }
  static const char* value(const ::core_api::SetHomeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CORE_API_MESSAGE_SETHOME_H
