// Generated by gencpp from file core_api/SetLED.msg
// DO NOT EDIT!


#ifndef CORE_API_MESSAGE_SETLED_H
#define CORE_API_MESSAGE_SETLED_H

#include <ros/service_traits.h>


#include <core_api/SetLEDRequest.h>
#include <core_api/SetLEDResponse.h>


namespace core_api
{

struct SetLED
{

typedef SetLEDRequest Request;
typedef SetLEDResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLED
} // namespace core_api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::core_api::SetLED > {
  static const char* value()
  {
    return "075d5cb58a54cdd3b1eee3d0d7b9c08b";
  }

  static const char* value(const ::core_api::SetLED&) { return value(); }
};

template<>
struct DataType< ::core_api::SetLED > {
  static const char* value()
  {
    return "core_api/SetLED";
  }

  static const char* value(const ::core_api::SetLED&) { return value(); }
};


// service_traits::MD5Sum< ::core_api::SetLEDRequest> should match 
// service_traits::MD5Sum< ::core_api::SetLED > 
template<>
struct MD5Sum< ::core_api::SetLEDRequest>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::SetLED >::value();
  }
  static const char* value(const ::core_api::SetLEDRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::SetLEDRequest> should match 
// service_traits::DataType< ::core_api::SetLED > 
template<>
struct DataType< ::core_api::SetLEDRequest>
{
  static const char* value()
  {
    return DataType< ::core_api::SetLED >::value();
  }
  static const char* value(const ::core_api::SetLEDRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::core_api::SetLEDResponse> should match 
// service_traits::MD5Sum< ::core_api::SetLED > 
template<>
struct MD5Sum< ::core_api::SetLEDResponse>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::SetLED >::value();
  }
  static const char* value(const ::core_api::SetLEDResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::SetLEDResponse> should match 
// service_traits::DataType< ::core_api::SetLED > 
template<>
struct DataType< ::core_api::SetLEDResponse>
{
  static const char* value()
  {
    return DataType< ::core_api::SetLED >::value();
  }
  static const char* value(const ::core_api::SetLEDResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CORE_API_MESSAGE_SETLED_H
