// Generated by gencpp from file core_api/TakeOff.msg
// DO NOT EDIT!


#ifndef CORE_API_MESSAGE_TAKEOFF_H
#define CORE_API_MESSAGE_TAKEOFF_H

#include <ros/service_traits.h>


#include <core_api/TakeOffRequest.h>
#include <core_api/TakeOffResponse.h>


namespace core_api
{

struct TakeOff
{

typedef TakeOffRequest Request;
typedef TakeOffResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TakeOff
} // namespace core_api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::core_api::TakeOff > {
  static const char* value()
  {
    return "8cfca9a26364ca62689da1c045d9ce94";
  }

  static const char* value(const ::core_api::TakeOff&) { return value(); }
};

template<>
struct DataType< ::core_api::TakeOff > {
  static const char* value()
  {
    return "core_api/TakeOff";
  }

  static const char* value(const ::core_api::TakeOff&) { return value(); }
};


// service_traits::MD5Sum< ::core_api::TakeOffRequest> should match 
// service_traits::MD5Sum< ::core_api::TakeOff > 
template<>
struct MD5Sum< ::core_api::TakeOffRequest>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::TakeOff >::value();
  }
  static const char* value(const ::core_api::TakeOffRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::TakeOffRequest> should match 
// service_traits::DataType< ::core_api::TakeOff > 
template<>
struct DataType< ::core_api::TakeOffRequest>
{
  static const char* value()
  {
    return DataType< ::core_api::TakeOff >::value();
  }
  static const char* value(const ::core_api::TakeOffRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::core_api::TakeOffResponse> should match 
// service_traits::MD5Sum< ::core_api::TakeOff > 
template<>
struct MD5Sum< ::core_api::TakeOffResponse>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::TakeOff >::value();
  }
  static const char* value(const ::core_api::TakeOffResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::TakeOffResponse> should match 
// service_traits::DataType< ::core_api::TakeOff > 
template<>
struct DataType< ::core_api::TakeOffResponse>
{
  static const char* value()
  {
    return DataType< ::core_api::TakeOff >::value();
  }
  static const char* value(const ::core_api::TakeOffResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CORE_API_MESSAGE_TAKEOFF_H
