// Generated by gencpp from file core_api/VelocitySet.msg
// DO NOT EDIT!


#ifndef CORE_API_MESSAGE_VELOCITYSET_H
#define CORE_API_MESSAGE_VELOCITYSET_H

#include <ros/service_traits.h>


#include <core_api/VelocitySetRequest.h>
#include <core_api/VelocitySetResponse.h>


namespace core_api
{

struct VelocitySet
{

typedef VelocitySetRequest Request;
typedef VelocitySetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VelocitySet
} // namespace core_api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::core_api::VelocitySet > {
  static const char* value()
  {
    return "4d8d96be58a2a2be16d36c94c6b850a1";
  }

  static const char* value(const ::core_api::VelocitySet&) { return value(); }
};

template<>
struct DataType< ::core_api::VelocitySet > {
  static const char* value()
  {
    return "core_api/VelocitySet";
  }

  static const char* value(const ::core_api::VelocitySet&) { return value(); }
};


// service_traits::MD5Sum< ::core_api::VelocitySetRequest> should match 
// service_traits::MD5Sum< ::core_api::VelocitySet > 
template<>
struct MD5Sum< ::core_api::VelocitySetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::VelocitySet >::value();
  }
  static const char* value(const ::core_api::VelocitySetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::VelocitySetRequest> should match 
// service_traits::DataType< ::core_api::VelocitySet > 
template<>
struct DataType< ::core_api::VelocitySetRequest>
{
  static const char* value()
  {
    return DataType< ::core_api::VelocitySet >::value();
  }
  static const char* value(const ::core_api::VelocitySetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::core_api::VelocitySetResponse> should match 
// service_traits::MD5Sum< ::core_api::VelocitySet > 
template<>
struct MD5Sum< ::core_api::VelocitySetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::VelocitySet >::value();
  }
  static const char* value(const ::core_api::VelocitySetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::VelocitySetResponse> should match 
// service_traits::DataType< ::core_api::VelocitySet > 
template<>
struct DataType< ::core_api::VelocitySetResponse>
{
  static const char* value()
  {
    return DataType< ::core_api::VelocitySet >::value();
  }
  static const char* value(const ::core_api::VelocitySetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CORE_API_MESSAGE_VELOCITYSET_H
