// Generated by gencpp from file core_api/WaypointClear.msg
// DO NOT EDIT!


#ifndef CORE_API_MESSAGE_WAYPOINTCLEAR_H
#define CORE_API_MESSAGE_WAYPOINTCLEAR_H

#include <ros/service_traits.h>


#include <core_api/WaypointClearRequest.h>
#include <core_api/WaypointClearResponse.h>


namespace core_api
{

struct WaypointClear
{

typedef WaypointClearRequest Request;
typedef WaypointClearResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WaypointClear
} // namespace core_api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::core_api::WaypointClear > {
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::core_api::WaypointClear&) { return value(); }
};

template<>
struct DataType< ::core_api::WaypointClear > {
  static const char* value()
  {
    return "core_api/WaypointClear";
  }

  static const char* value(const ::core_api::WaypointClear&) { return value(); }
};


// service_traits::MD5Sum< ::core_api::WaypointClearRequest> should match 
// service_traits::MD5Sum< ::core_api::WaypointClear > 
template<>
struct MD5Sum< ::core_api::WaypointClearRequest>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::WaypointClear >::value();
  }
  static const char* value(const ::core_api::WaypointClearRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::WaypointClearRequest> should match 
// service_traits::DataType< ::core_api::WaypointClear > 
template<>
struct DataType< ::core_api::WaypointClearRequest>
{
  static const char* value()
  {
    return DataType< ::core_api::WaypointClear >::value();
  }
  static const char* value(const ::core_api::WaypointClearRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::core_api::WaypointClearResponse> should match 
// service_traits::MD5Sum< ::core_api::WaypointClear > 
template<>
struct MD5Sum< ::core_api::WaypointClearResponse>
{
  static const char* value()
  {
    return MD5Sum< ::core_api::WaypointClear >::value();
  }
  static const char* value(const ::core_api::WaypointClearResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::core_api::WaypointClearResponse> should match 
// service_traits::DataType< ::core_api::WaypointClear > 
template<>
struct DataType< ::core_api::WaypointClearResponse>
{
  static const char* value()
  {
    return DataType< ::core_api::WaypointClear >::value();
  }
  static const char* value(const ::core_api::WaypointClearResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CORE_API_MESSAGE_WAYPOINTCLEAR_H
