// Generated by gencpp from file navigation_util/NavigationVelGoal.msg
// DO NOT EDIT!


#ifndef NAVIGATION_UTIL_MESSAGE_NAVIGATIONVELGOAL_H
#define NAVIGATION_UTIL_MESSAGE_NAVIGATIONVELGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/TwistStamped.h>

namespace navigation_util
{
template <class ContainerAllocator>
struct NavigationVelGoal_
{
  typedef NavigationVelGoal_<ContainerAllocator> Type;

  NavigationVelGoal_()
    : twist()
    , tolerance(0.0)
    , alt_rate_invalid(false)  {
    }
  NavigationVelGoal_(const ContainerAllocator& _alloc)
    : twist(_alloc)
    , tolerance(0.0)
    , alt_rate_invalid(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::TwistStamped_<ContainerAllocator>  _twist_type;
  _twist_type twist;

   typedef float _tolerance_type;
  _tolerance_type tolerance;

   typedef uint8_t _alt_rate_invalid_type;
  _alt_rate_invalid_type alt_rate_invalid;





  typedef boost::shared_ptr< ::navigation_util::NavigationVelGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation_util::NavigationVelGoal_<ContainerAllocator> const> ConstPtr;

}; // struct NavigationVelGoal_

typedef ::navigation_util::NavigationVelGoal_<std::allocator<void> > NavigationVelGoal;

typedef boost::shared_ptr< ::navigation_util::NavigationVelGoal > NavigationVelGoalPtr;
typedef boost::shared_ptr< ::navigation_util::NavigationVelGoal const> NavigationVelGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation_util::NavigationVelGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation_util::NavigationVelGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navigation_util

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'navigation_util': ['/home/flytpod/flytos/amd64-devel/share/navigation_util/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navigation_util::NavigationVelGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation_util::NavigationVelGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_util::NavigationVelGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_util::NavigationVelGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_util::NavigationVelGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_util::NavigationVelGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation_util::NavigationVelGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51eb06e58e458bb85a09fb8613e3c5b0";
  }

  static const char* value(const ::navigation_util::NavigationVelGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51eb06e58e458bb8ULL;
  static const uint64_t static_value2 = 0x5a09fb8613e3c5b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation_util::NavigationVelGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation_util/NavigationVelGoal";
  }

  static const char* value(const ::navigation_util::NavigationVelGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation_util::NavigationVelGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
geometry_msgs/TwistStamped twist\n\
\n\
#Termination criterion, in terms of sum of squared error per dimension\n\
float32 tolerance\n\
bool alt_rate_invalid\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/TwistStamped\n\
# A twist with reference coordinate frame and timestamp\n\
Header header\n\
Twist twist\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::navigation_util::NavigationVelGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation_util::NavigationVelGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.twist);
      stream.next(m.tolerance);
      stream.next(m.alt_rate_invalid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigationVelGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation_util::NavigationVelGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation_util::NavigationVelGoal_<ContainerAllocator>& v)
  {
    s << indent << "twist: ";
    s << std::endl;
    Printer< ::geometry_msgs::TwistStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.twist);
    s << indent << "tolerance: ";
    Printer<float>::stream(s, indent + "  ", v.tolerance);
    s << indent << "alt_rate_invalid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.alt_rate_invalid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_UTIL_MESSAGE_NAVIGATIONVELGOAL_H
