// Generated by gencpp from file vision_apps/GetCurrrentCheckpointResponse.msg
// DO NOT EDIT!


#ifndef VISION_APPS_MESSAGE_GETCURRRENTCHECKPOINTRESPONSE_H
#define VISION_APPS_MESSAGE_GETCURRRENTCHECKPOINTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision_apps
{
template <class ContainerAllocator>
struct GetCurrrentCheckpointResponse_
{
  typedef GetCurrrentCheckpointResponse_<ContainerAllocator> Type;

  GetCurrrentCheckpointResponse_()
    : success(false)
    , error_code(0)
    , checkpoint_id(0)
    , missionpoint_number(0)
    , tag_id(0)
    , message()  {
    }
  GetCurrrentCheckpointResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , error_code(0)
    , checkpoint_id(0)
    , missionpoint_number(0)
    , tag_id(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef uint8_t _error_code_type;
  _error_code_type error_code;

   typedef uint8_t _checkpoint_id_type;
  _checkpoint_id_type checkpoint_id;

   typedef uint8_t _missionpoint_number_type;
  _missionpoint_number_type missionpoint_number;

   typedef uint8_t _tag_id_type;
  _tag_id_type tag_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::vision_apps::GetCurrrentCheckpointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_apps::GetCurrrentCheckpointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetCurrrentCheckpointResponse_

typedef ::vision_apps::GetCurrrentCheckpointResponse_<std::allocator<void> > GetCurrrentCheckpointResponse;

typedef boost::shared_ptr< ::vision_apps::GetCurrrentCheckpointResponse > GetCurrrentCheckpointResponsePtr;
typedef boost::shared_ptr< ::vision_apps::GetCurrrentCheckpointResponse const> GetCurrrentCheckpointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_apps::GetCurrrentCheckpointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_apps::GetCurrrentCheckpointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision_apps

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'vision_apps': ['/home/flytpod/flytos/src/flytOS/flyt_packages/vision/vision_nodes/msg', '/home/flytpod/flytos/amd64-devel/share/vision_apps/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision_apps::GetCurrrentCheckpointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_apps::GetCurrrentCheckpointResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_apps::GetCurrrentCheckpointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_apps::GetCurrrentCheckpointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_apps::GetCurrrentCheckpointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_apps::GetCurrrentCheckpointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_apps::GetCurrrentCheckpointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7cc3faa051aab17ce96e020c0c4d1fb6";
  }

  static const char* value(const ::vision_apps::GetCurrrentCheckpointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7cc3faa051aab17cULL;
  static const uint64_t static_value2 = 0xe96e020c0c4d1fb6ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_apps::GetCurrrentCheckpointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_apps/GetCurrrentCheckpointResponse";
  }

  static const char* value(const ::vision_apps::GetCurrrentCheckpointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_apps::GetCurrrentCheckpointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
uint8 error_code\n\
uint8 checkpoint_id\n\
uint8 missionpoint_number\n\
uint8 tag_id\n\
string message\n\
\n\
";
  }

  static const char* value(const ::vision_apps::GetCurrrentCheckpointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_apps::GetCurrrentCheckpointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.error_code);
      stream.next(m.checkpoint_id);
      stream.next(m.missionpoint_number);
      stream.next(m.tag_id);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetCurrrentCheckpointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_apps::GetCurrrentCheckpointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_apps::GetCurrrentCheckpointResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "error_code: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "checkpoint_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.checkpoint_id);
    s << indent << "missionpoint_number: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.missionpoint_number);
    s << indent << "tag_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tag_id);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_APPS_MESSAGE_GETCURRRENTCHECKPOINTRESPONSE_H
