// Generated by gencpp from file vision_apps/GetTagsNavigation.msg
// DO NOT EDIT!


#ifndef VISION_APPS_MESSAGE_GETTAGSNAVIGATION_H
#define VISION_APPS_MESSAGE_GETTAGSNAVIGATION_H

#include <ros/service_traits.h>


#include <vision_apps/GetTagsNavigationRequest.h>
#include <vision_apps/GetTagsNavigationResponse.h>


namespace vision_apps
{

struct GetTagsNavigation
{

typedef GetTagsNavigationRequest Request;
typedef GetTagsNavigationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTagsNavigation
} // namespace vision_apps


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vision_apps::GetTagsNavigation > {
  static const char* value()
  {
    return "53782a4fae57c38fe64c9c19dae267f7";
  }

  static const char* value(const ::vision_apps::GetTagsNavigation&) { return value(); }
};

template<>
struct DataType< ::vision_apps::GetTagsNavigation > {
  static const char* value()
  {
    return "vision_apps/GetTagsNavigation";
  }

  static const char* value(const ::vision_apps::GetTagsNavigation&) { return value(); }
};


// service_traits::MD5Sum< ::vision_apps::GetTagsNavigationRequest> should match 
// service_traits::MD5Sum< ::vision_apps::GetTagsNavigation > 
template<>
struct MD5Sum< ::vision_apps::GetTagsNavigationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vision_apps::GetTagsNavigation >::value();
  }
  static const char* value(const ::vision_apps::GetTagsNavigationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision_apps::GetTagsNavigationRequest> should match 
// service_traits::DataType< ::vision_apps::GetTagsNavigation > 
template<>
struct DataType< ::vision_apps::GetTagsNavigationRequest>
{
  static const char* value()
  {
    return DataType< ::vision_apps::GetTagsNavigation >::value();
  }
  static const char* value(const ::vision_apps::GetTagsNavigationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vision_apps::GetTagsNavigationResponse> should match 
// service_traits::MD5Sum< ::vision_apps::GetTagsNavigation > 
template<>
struct MD5Sum< ::vision_apps::GetTagsNavigationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vision_apps::GetTagsNavigation >::value();
  }
  static const char* value(const ::vision_apps::GetTagsNavigationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision_apps::GetTagsNavigationResponse> should match 
// service_traits::DataType< ::vision_apps::GetTagsNavigation > 
template<>
struct DataType< ::vision_apps::GetTagsNavigationResponse>
{
  static const char* value()
  {
    return DataType< ::vision_apps::GetTagsNavigation >::value();
  }
  static const char* value(const ::vision_apps::GetTagsNavigationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VISION_APPS_MESSAGE_GETTAGSNAVIGATION_H
