// Generated by gencpp from file vision_apps/LoadCheckpoints.msg
// DO NOT EDIT!


#ifndef VISION_APPS_MESSAGE_LOADCHECKPOINTS_H
#define VISION_APPS_MESSAGE_LOADCHECKPOINTS_H

#include <ros/service_traits.h>


#include <vision_apps/LoadCheckpointsRequest.h>
#include <vision_apps/LoadCheckpointsResponse.h>


namespace vision_apps
{

struct LoadCheckpoints
{

typedef LoadCheckpointsRequest Request;
typedef LoadCheckpointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadCheckpoints
} // namespace vision_apps


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vision_apps::LoadCheckpoints > {
  static const char* value()
  {
    return "0716ca053acdca4ffd9f1606f16f3814";
  }

  static const char* value(const ::vision_apps::LoadCheckpoints&) { return value(); }
};

template<>
struct DataType< ::vision_apps::LoadCheckpoints > {
  static const char* value()
  {
    return "vision_apps/LoadCheckpoints";
  }

  static const char* value(const ::vision_apps::LoadCheckpoints&) { return value(); }
};


// service_traits::MD5Sum< ::vision_apps::LoadCheckpointsRequest> should match 
// service_traits::MD5Sum< ::vision_apps::LoadCheckpoints > 
template<>
struct MD5Sum< ::vision_apps::LoadCheckpointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vision_apps::LoadCheckpoints >::value();
  }
  static const char* value(const ::vision_apps::LoadCheckpointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision_apps::LoadCheckpointsRequest> should match 
// service_traits::DataType< ::vision_apps::LoadCheckpoints > 
template<>
struct DataType< ::vision_apps::LoadCheckpointsRequest>
{
  static const char* value()
  {
    return DataType< ::vision_apps::LoadCheckpoints >::value();
  }
  static const char* value(const ::vision_apps::LoadCheckpointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vision_apps::LoadCheckpointsResponse> should match 
// service_traits::MD5Sum< ::vision_apps::LoadCheckpoints > 
template<>
struct MD5Sum< ::vision_apps::LoadCheckpointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vision_apps::LoadCheckpoints >::value();
  }
  static const char* value(const ::vision_apps::LoadCheckpointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision_apps::LoadCheckpointsResponse> should match 
// service_traits::DataType< ::vision_apps::LoadCheckpoints > 
template<>
struct DataType< ::vision_apps::LoadCheckpointsResponse>
{
  static const char* value()
  {
    return DataType< ::vision_apps::LoadCheckpoints >::value();
  }
  static const char* value(const ::vision_apps::LoadCheckpointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VISION_APPS_MESSAGE_LOADCHECKPOINTS_H
