// Generated by gencpp from file vision_apps/SetCheckpoints.msg
// DO NOT EDIT!


#ifndef VISION_APPS_MESSAGE_SETCHECKPOINTS_H
#define VISION_APPS_MESSAGE_SETCHECKPOINTS_H

#include <ros/service_traits.h>


#include <vision_apps/SetCheckpointsRequest.h>
#include <vision_apps/SetCheckpointsResponse.h>


namespace vision_apps
{

struct SetCheckpoints
{

typedef SetCheckpointsRequest Request;
typedef SetCheckpointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCheckpoints
} // namespace vision_apps


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vision_apps::SetCheckpoints > {
  static const char* value()
  {
    return "5b6a36f86958efb1c0227d47b297cadc";
  }

  static const char* value(const ::vision_apps::SetCheckpoints&) { return value(); }
};

template<>
struct DataType< ::vision_apps::SetCheckpoints > {
  static const char* value()
  {
    return "vision_apps/SetCheckpoints";
  }

  static const char* value(const ::vision_apps::SetCheckpoints&) { return value(); }
};


// service_traits::MD5Sum< ::vision_apps::SetCheckpointsRequest> should match 
// service_traits::MD5Sum< ::vision_apps::SetCheckpoints > 
template<>
struct MD5Sum< ::vision_apps::SetCheckpointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vision_apps::SetCheckpoints >::value();
  }
  static const char* value(const ::vision_apps::SetCheckpointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision_apps::SetCheckpointsRequest> should match 
// service_traits::DataType< ::vision_apps::SetCheckpoints > 
template<>
struct DataType< ::vision_apps::SetCheckpointsRequest>
{
  static const char* value()
  {
    return DataType< ::vision_apps::SetCheckpoints >::value();
  }
  static const char* value(const ::vision_apps::SetCheckpointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vision_apps::SetCheckpointsResponse> should match 
// service_traits::MD5Sum< ::vision_apps::SetCheckpoints > 
template<>
struct MD5Sum< ::vision_apps::SetCheckpointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vision_apps::SetCheckpoints >::value();
  }
  static const char* value(const ::vision_apps::SetCheckpointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision_apps::SetCheckpointsResponse> should match 
// service_traits::DataType< ::vision_apps::SetCheckpoints > 
template<>
struct DataType< ::vision_apps::SetCheckpointsResponse>
{
  static const char* value()
  {
    return DataType< ::vision_apps::SetCheckpoints >::value();
  }
  static const char* value(const ::vision_apps::SetCheckpointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VISION_APPS_MESSAGE_SETCHECKPOINTS_H
