// Generated by gencpp from file vision_apps/SetLandingTagsRequest.msg
// DO NOT EDIT!


#ifndef VISION_APPS_MESSAGE_SETLANDINGTAGSREQUEST_H
#define VISION_APPS_MESSAGE_SETLANDINGTAGSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision_apps
{
template <class ContainerAllocator>
struct SetLandingTagsRequest_
{
  typedef SetLandingTagsRequest_<ContainerAllocator> Type;

  SetLandingTagsRequest_()
    : tags_list()
    , tags_size()
    , save(false)  {
    }
  SetLandingTagsRequest_(const ContainerAllocator& _alloc)
    : tags_list(_alloc)
    , tags_size(_alloc)
    , save(false)  {
  (void)_alloc;
    }



   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _tags_list_type;
  _tags_list_type tags_list;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _tags_size_type;
  _tags_size_type tags_size;

   typedef uint8_t _save_type;
  _save_type save;





  typedef boost::shared_ptr< ::vision_apps::SetLandingTagsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_apps::SetLandingTagsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetLandingTagsRequest_

typedef ::vision_apps::SetLandingTagsRequest_<std::allocator<void> > SetLandingTagsRequest;

typedef boost::shared_ptr< ::vision_apps::SetLandingTagsRequest > SetLandingTagsRequestPtr;
typedef boost::shared_ptr< ::vision_apps::SetLandingTagsRequest const> SetLandingTagsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_apps::SetLandingTagsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_apps::SetLandingTagsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision_apps

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'vision_apps': ['/home/flytpod/flytos/src/flytOS/flyt_packages/vision/vision_nodes/msg', '/home/flytpod/flytos/amd64-devel/share/vision_apps/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision_apps::SetLandingTagsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_apps::SetLandingTagsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_apps::SetLandingTagsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_apps::SetLandingTagsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_apps::SetLandingTagsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_apps::SetLandingTagsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_apps::SetLandingTagsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bbb6b6df56128886e3d664be49a1a4eb";
  }

  static const char* value(const ::vision_apps::SetLandingTagsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbbb6b6df56128886ULL;
  static const uint64_t static_value2 = 0xe3d664be49a1a4ebULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_apps::SetLandingTagsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_apps/SetLandingTagsRequest";
  }

  static const char* value(const ::vision_apps::SetLandingTagsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_apps::SetLandingTagsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16[] tags_list\n\
float32[] tags_size\n\
bool save\n\
";
  }

  static const char* value(const ::vision_apps::SetLandingTagsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_apps::SetLandingTagsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tags_list);
      stream.next(m.tags_size);
      stream.next(m.save);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetLandingTagsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_apps::SetLandingTagsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_apps::SetLandingTagsRequest_<ContainerAllocator>& v)
  {
    s << indent << "tags_list[]" << std::endl;
    for (size_t i = 0; i < v.tags_list.size(); ++i)
    {
      s << indent << "  tags_list[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.tags_list[i]);
    }
    s << indent << "tags_size[]" << std::endl;
    for (size_t i = 0; i < v.tags_size.size(); ++i)
    {
      s << indent << "  tags_size[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.tags_size[i]);
    }
    s << indent << "save: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.save);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_APPS_MESSAGE_SETLANDINGTAGSREQUEST_H
