// Generated by gencpp from file vision_apps/SetMissionRequest.msg
// DO NOT EDIT!


#ifndef VISION_APPS_MESSAGE_SETMISSIONREQUEST_H
#define VISION_APPS_MESSAGE_SETMISSIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision_apps
{
template <class ContainerAllocator>
struct SetMissionRequest_
{
  typedef SetMissionRequest_<ContainerAllocator> Type;

  SetMissionRequest_()
    : mission()  {
    }
  SetMissionRequest_(const ContainerAllocator& _alloc)
    : mission(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _mission_type;
  _mission_type mission;





  typedef boost::shared_ptr< ::vision_apps::SetMissionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_apps::SetMissionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetMissionRequest_

typedef ::vision_apps::SetMissionRequest_<std::allocator<void> > SetMissionRequest;

typedef boost::shared_ptr< ::vision_apps::SetMissionRequest > SetMissionRequestPtr;
typedef boost::shared_ptr< ::vision_apps::SetMissionRequest const> SetMissionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_apps::SetMissionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_apps::SetMissionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision_apps

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'vision_apps': ['/home/flytpod/flytos/src/flytOS/flyt_packages/vision/vision_nodes/msg', '/home/flytpod/flytos/amd64-devel/share/vision_apps/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision_apps::SetMissionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_apps::SetMissionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_apps::SetMissionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_apps::SetMissionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_apps::SetMissionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_apps::SetMissionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_apps::SetMissionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6324920e132b2970ec7a4613bf7fb217";
  }

  static const char* value(const ::vision_apps::SetMissionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6324920e132b2970ULL;
  static const uint64_t static_value2 = 0xec7a4613bf7fb217ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_apps::SetMissionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_apps/SetMissionRequest";
  }

  static const char* value(const ::vision_apps::SetMissionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_apps::SetMissionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16[] mission\n\
";
  }

  static const char* value(const ::vision_apps::SetMissionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_apps::SetMissionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mission);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetMissionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_apps::SetMissionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_apps::SetMissionRequest_<ContainerAllocator>& v)
  {
    s << indent << "mission[]" << std::endl;
    for (size_t i = 0; i < v.mission.size(); ++i)
    {
      s << indent << "  mission[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.mission[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_APPS_MESSAGE_SETMISSIONREQUEST_H
