// Generated by gencpp from file vision_apps/StartCameraCaptureRequest.msg
// DO NOT EDIT!


#ifndef VISION_APPS_MESSAGE_STARTCAMERACAPTUREREQUEST_H
#define VISION_APPS_MESSAGE_STARTCAMERACAPTUREREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision_apps
{
template <class ContainerAllocator>
struct StartCameraCaptureRequest_
{
  typedef StartCameraCaptureRequest_<ContainerAllocator> Type;

  StartCameraCaptureRequest_()
    : camera_alias()
    , pixel_format()
    , image_width(0)
    , image_height(0)
    , framerate(0)
    , brightness(0)
    , camera_info_url()  {
    }
  StartCameraCaptureRequest_(const ContainerAllocator& _alloc)
    : camera_alias(_alloc)
    , pixel_format(_alloc)
    , image_width(0)
    , image_height(0)
    , framerate(0)
    , brightness(0)
    , camera_info_url(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _camera_alias_type;
  _camera_alias_type camera_alias;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _pixel_format_type;
  _pixel_format_type pixel_format;

   typedef int64_t _image_width_type;
  _image_width_type image_width;

   typedef int64_t _image_height_type;
  _image_height_type image_height;

   typedef int64_t _framerate_type;
  _framerate_type framerate;

   typedef int64_t _brightness_type;
  _brightness_type brightness;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _camera_info_url_type;
  _camera_info_url_type camera_info_url;





  typedef boost::shared_ptr< ::vision_apps::StartCameraCaptureRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_apps::StartCameraCaptureRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartCameraCaptureRequest_

typedef ::vision_apps::StartCameraCaptureRequest_<std::allocator<void> > StartCameraCaptureRequest;

typedef boost::shared_ptr< ::vision_apps::StartCameraCaptureRequest > StartCameraCaptureRequestPtr;
typedef boost::shared_ptr< ::vision_apps::StartCameraCaptureRequest const> StartCameraCaptureRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_apps::StartCameraCaptureRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_apps::StartCameraCaptureRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision_apps

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'vision_apps': ['/home/flytpod/flytos/src/flytOS/flyt_packages/vision/vision_nodes/msg', '/home/flytpod/flytos/amd64-devel/share/vision_apps/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision_apps::StartCameraCaptureRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_apps::StartCameraCaptureRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_apps::StartCameraCaptureRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_apps::StartCameraCaptureRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_apps::StartCameraCaptureRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_apps::StartCameraCaptureRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_apps::StartCameraCaptureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c07f5d9a8fa4e366c0359eb63b05431c";
  }

  static const char* value(const ::vision_apps::StartCameraCaptureRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc07f5d9a8fa4e366ULL;
  static const uint64_t static_value2 = 0xc0359eb63b05431cULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_apps::StartCameraCaptureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_apps/StartCameraCaptureRequest";
  }

  static const char* value(const ::vision_apps::StartCameraCaptureRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_apps::StartCameraCaptureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string camera_alias\n\
string pixel_format\n\
int64  image_width\n\
int64  image_height\n\
int64  framerate\n\
int64  brightness\n\
string camera_info_url\n\
";
  }

  static const char* value(const ::vision_apps::StartCameraCaptureRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_apps::StartCameraCaptureRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.camera_alias);
      stream.next(m.pixel_format);
      stream.next(m.image_width);
      stream.next(m.image_height);
      stream.next(m.framerate);
      stream.next(m.brightness);
      stream.next(m.camera_info_url);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartCameraCaptureRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_apps::StartCameraCaptureRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_apps::StartCameraCaptureRequest_<ContainerAllocator>& v)
  {
    s << indent << "camera_alias: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.camera_alias);
    s << indent << "pixel_format: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.pixel_format);
    s << indent << "image_width: ";
    Printer<int64_t>::stream(s, indent + "  ", v.image_width);
    s << indent << "image_height: ";
    Printer<int64_t>::stream(s, indent + "  ", v.image_height);
    s << indent << "framerate: ";
    Printer<int64_t>::stream(s, indent + "  ", v.framerate);
    s << indent << "brightness: ";
    Printer<int64_t>::stream(s, indent + "  ", v.brightness);
    s << indent << "camera_info_url: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.camera_info_url);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_APPS_MESSAGE_STARTCAMERACAPTUREREQUEST_H
