// Generated by gencpp from file cpp_api/UserData.msg
// DO NOT EDIT!


#ifndef CPP_API_MESSAGE_USERDATA_H
#define CPP_API_MESSAGE_USERDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace cpp_api
{
template <class ContainerAllocator>
struct UserData_
{
  typedef UserData_<ContainerAllocator> Type;

  UserData_()
    : header()
    , data_string()
    , data_double()  {
    }
  UserData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data_string(_alloc)
    , data_double(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _data_string_type;
  _data_string_type data_string;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _data_double_type;
  _data_double_type data_double;





  typedef boost::shared_ptr< ::cpp_api::UserData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cpp_api::UserData_<ContainerAllocator> const> ConstPtr;

}; // struct UserData_

typedef ::cpp_api::UserData_<std::allocator<void> > UserData;

typedef boost::shared_ptr< ::cpp_api::UserData > UserDataPtr;
typedef boost::shared_ptr< ::cpp_api::UserData const> UserDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cpp_api::UserData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cpp_api::UserData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cpp_api

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'cpp_api': ['/home/flytpod/flytos/src/flytOS/flyt_core/core_script_bridge/cpp_api/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cpp_api::UserData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpp_api::UserData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpp_api::UserData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpp_api::UserData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpp_api::UserData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpp_api::UserData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cpp_api::UserData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e1b785877a526c8a4bf870310420a136";
  }

  static const char* value(const ::cpp_api::UserData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe1b785877a526c8aULL;
  static const uint64_t static_value2 = 0x4bf870310420a136ULL;
};

template<class ContainerAllocator>
struct DataType< ::cpp_api::UserData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cpp_api/UserData";
  }

  static const char* value(const ::cpp_api::UserData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cpp_api::UserData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
string[] data_string\n\
float64[] data_double\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::cpp_api::UserData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cpp_api::UserData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data_string);
      stream.next(m.data_double);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UserData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cpp_api::UserData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cpp_api::UserData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data_string[]" << std::endl;
    for (size_t i = 0; i < v.data_string.size(); ++i)
    {
      s << indent << "  data_string[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data_string[i]);
    }
    s << indent << "data_double[]" << std::endl;
    for (size_t i = 0; i < v.data_double.size(); ++i)
    {
      s << indent << "  data_double[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data_double[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CPP_API_MESSAGE_USERDATA_H
