#!/usr/bin/env python
"""@package precision_controller
"""
from vision_apps.msg import *
from vision_apps.srv import *

from indoor_navigation import indoor_navigation_action_server
indoor_navigation_action_server.main()
