#!/usr/bin/env python
"""@package precision_controller
"""

from vision_apps.msg import *
from vision_apps.srv import *

from precision_landing import precision_landing_action_server
precision_landing_action_server.main()
