// Generated by gencpp from file maxbotix/ChangeAddress.msg
// DO NOT EDIT!


#ifndef MAXBOTIX_MESSAGE_CHANGEADDRESS_H
#define MAXBOTIX_MESSAGE_CHANGEADDRESS_H

#include <ros/service_traits.h>


#include <maxbotix/ChangeAddressRequest.h>
#include <maxbotix/ChangeAddressResponse.h>


namespace maxbotix
{

struct ChangeAddress
{

typedef ChangeAddressRequest Request;
typedef ChangeAddressResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeAddress
} // namespace maxbotix


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::maxbotix::ChangeAddress > {
  static const char* value()
  {
    return "679a57e3b3b49facc4662b8ff5dd2743";
  }

  static const char* value(const ::maxbotix::ChangeAddress&) { return value(); }
};

template<>
struct DataType< ::maxbotix::ChangeAddress > {
  static const char* value()
  {
    return "maxbotix/ChangeAddress";
  }

  static const char* value(const ::maxbotix::ChangeAddress&) { return value(); }
};


// service_traits::MD5Sum< ::maxbotix::ChangeAddressRequest> should match 
// service_traits::MD5Sum< ::maxbotix::ChangeAddress > 
template<>
struct MD5Sum< ::maxbotix::ChangeAddressRequest>
{
  static const char* value()
  {
    return MD5Sum< ::maxbotix::ChangeAddress >::value();
  }
  static const char* value(const ::maxbotix::ChangeAddressRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::maxbotix::ChangeAddressRequest> should match 
// service_traits::DataType< ::maxbotix::ChangeAddress > 
template<>
struct DataType< ::maxbotix::ChangeAddressRequest>
{
  static const char* value()
  {
    return DataType< ::maxbotix::ChangeAddress >::value();
  }
  static const char* value(const ::maxbotix::ChangeAddressRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::maxbotix::ChangeAddressResponse> should match 
// service_traits::MD5Sum< ::maxbotix::ChangeAddress > 
template<>
struct MD5Sum< ::maxbotix::ChangeAddressResponse>
{
  static const char* value()
  {
    return MD5Sum< ::maxbotix::ChangeAddress >::value();
  }
  static const char* value(const ::maxbotix::ChangeAddressResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::maxbotix::ChangeAddressResponse> should match 
// service_traits::DataType< ::maxbotix::ChangeAddress > 
template<>
struct DataType< ::maxbotix::ChangeAddressResponse>
{
  static const char* value()
  {
    return DataType< ::maxbotix::ChangeAddress >::value();
  }
  static const char* value(const ::maxbotix::ChangeAddressResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAXBOTIX_MESSAGE_CHANGEADDRESS_H
