uint8 MAV_TYPE_GENERIC=0
uint8 MAV_TYPE_FIXED_WING=1
uint8 MAV_TYPE_QUADROTOR=2
uint8 MAV_TYPE_COAXIAL=3
uint8 MAV_TYPE_HELICOPTER=4
uint8 MAV_TYPE_ANTENNA_TRACKER=5
uint8 MAV_TYPE_GCS=6
uint8 MAV_TYPE_AIRSHIP=7
uint8 MAV_TYPE_FREE_BALLOON=8
uint8 MAV_TYPE_ROCKET=9
uint8 MAV_TYPE_GROUND_ROVER=10
uint8 MAV_TYPE_SURFACE_BOAT=11
uint8 MAV_TYPE_SUBMARINE=12
uint8 MAV_TYPE_HEXAROTOR=13
uint8 MAV_TYPE_OCTOROTOR=14
uint8 MAV_TYPE_TRICOPTER=15
uint8 MAV_TYPE_FLAPPING_WING=16
uint8 MAV_TYPE_KITE=17
uint8 MAV_TYPE_ONBOARD_CONTROLLER=18
uint8 MAV_TYPE_VTOL_DUOROTOR=19
uint8 MAV_TYPE_VTOL_QUADROTOR=20
uint8 MAV_TYPE_VTOL_TILTROTOR=21
uint8 MAV_TYPE_VTOL_RESERVED2=22
uint8 MAV_TYPE_VTOL_RESERVED3=23
uint8 MAV_TYPE_VTOL_RESERVED4=24
uint8 MAV_TYPE_VTOL_RESERVED5=25
uint8 MAV_TYPE_GIMBAL=26
uint8 MAV_TYPE_ADSB=27

---
bool success
uint8 frame_type
string message
